bind = "0.0.0.0"
port = 6379
databases = 16
#requirepass = "admin"

logfile = "./logs/redis.log"
# debug | info | warn | error
loglevel = "debug"

appendonly = true
appendfilename = "appendonly.aof"
appendfsync = "everysec"
#appendfsync = "always"
#appendfsync = "no"

auto-aof-rewrite-percentage = 100
auto-aof-rewrite-min-size = "64mb"